experiment:
  name: exp002

data:
  target: 購入フラグ
  id: 企業ID

feature:
  drop_columns:
    - 企業名
    - 企業概要
    - 組織図
    - 今後のDX展望
  
  categorical_features:
    - 業界
    - 上場種別
    - 特徴

cv:
  n_splits: 5
  random_state: 42
  shuffle: true

model:
  objective: binary
  metric: auc
  learning_rate: 0.05
  num_leaves: 63
  max_depth: -1
  feature_fraction: 0.8
  bagging_fraction: 0.8
  bagging_freq: 1
  n_estimators: 5000

train:
  early_stopping_rounds: 100